include Makefile.setup
include config.mk

all:
	echo "prefix=$(prefix)" > egl.pc
	cat egl.pc.in >> egl.pc
	echo "prefix=$(prefix)" > gles_cm.pc
	cat egl.pc.in >> gles_cm.pc
	echo "prefix=$(prefix)" > glesv2.pc
	cat egl.pc.in >> glesv2.pc

install: egl.pc gles_cm.pc glesv2.pc
	$(MKDIR) $(libdir)/pkgconfig
	$(INSTALL_DATA) $^ $(libdir)/pkgconfig

clean:
	$(RM) egl.pc gles_cm.pc glesv2.pc

