all: unknown

clean:
	$(MAKE) -C version clean
	$(MAKE) -C test clean

install: unknown
unknown:
	@echo ""
	@echo "Do read the README first."
	@echo ""

framebuffer:
	$(MAKE) -C mali framebuffer

x11:
	$(MAKE) -C mali x11

