all: unknown

clean:
	$(MAKE) -C ump clean

install: unknown
unknown:
	@echo ""
	@echo "Do read the README first."
	@echo ""

framebuffer:
	$(MAKE) -C ump framebuffer
	$(MAKE) -C mali framebuffer

x11:
	$(MAKE) -C ump x11
	$(MAKE) -C mali x11

